export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const SET_PRODUCT_PAGE = 'SET_PRODUCT_PAGE';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
